## This file contain various Pandas exercises and their solutions.  It is intended for practice and learning purposes.

In [1]:
import pandas
import pandas as pd

### *The following exercises are based on the Pynative Exercises: https://pynative.com/python-pandas-exercise/ and the correlated dataset.*

#### 1. Let's start with a simple exercise. Read the dataset 'Automobile_data.csv' and report the number of rows and the title of the different columns.

In [2]:
dataframe = pd.read_csv('Automobile_data.csv')

print(len(dataframe))
titles = list(dataframe.columns)
print(titles)

61
['index', 'company', 'body-style', 'wheel-base', 'length', 'engine-type', 'num-of-cylinders', 'horsepower', 'average-mileage', 'price']

In [3]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB

#### 2. Now print the first 5 and the last 5 rows of the dataset.

In [5]:
# First approach: manual iteration over the file

for ind,rows in enumerate(dataframe.values):
    if ind < 5:
        print(rows)
print()

for rows in dataframe.values[-5:]:
    print(rows)

# Second approach:  Pandas methods

dataframe.head(5)
dataframe.tail(5)

[0 'alfa-romero' 'convertible' 88.6 168.8 'dohc' 'four' 111 21 13495.0]
[1 'alfa-romero' 'convertible' 88.6 168.8 'dohc' 'four' 111 21 16500.0]
[2 'alfa-romero' 'hatchback' 94.5 171.2 'ohcv' 'six' 154 19 16500.0]
[3 'audi' 'sedan' 99.8 176.6 'ohc' 'four' 102 24 13950.0]
[4 'audi' 'sedan' 99.4 176.6 'ohc' 'five' 115 18 17450.0]

[81 'volkswagen' 'sedan' 97.3 171.7 'ohc' 'four' 85 27 7975.0]
[82 'volkswagen' 'sedan' 97.3 171.7 'ohc' 'four' 52 37 7995.0]
[86 'volkswagen' 'sedan' 97.3 171.7 'ohc' 'four' 100 26 9995.0]
[87 'volvo' 'sedan' 104.3 188.8 'ohc' 'four' 114 23 12940.0]
[88 'volvo' 'wagon' 104.3 188.8 'ohc' 'four' 114 23 13415.0]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [4]:
# In order to show all the parts needed as asked, we need to import display.

from IPython.display import display

display(dataframe.head(5))

display(dataframe.tail(5))

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

#### 3. Clean the dataset by removing the '?' character from the dataset. Replace it with N.a. and then print the cleaned dataset.

In [6]:
dataframe.replace(['?', 'n.a.'])

C:\Users\zanca\AppData\Local\Temp\ipykernel_11024\1542428481.py:1: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  dataframe.replace(['?', 'n.a.'])

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

#### 4. Find the most expensive car and print its name and price.

In [9]:
display(dataframe[dataframe['price'] == dataframe['price'].max()])

dataframe[dataframe['price'] == dataframe['price'].max()][['company','price']]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0

          company    price
35  mercedes-benz  45400.0

#### 5. Print only the rows of a specific car company.

In [10]:
# First Option: boolean filtering
display(dataframe[dataframe['company'] == 'volvo'])
print()

# Second Option: Pandas methods
volvo_cars = dataframe.groupby('company').get_group('volvo')
volvo_cars

# extra condition
new_data = pd.DataFrame(volvo_cars)
display(new_data[new_data['body-style'] == 'sedan'])

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0

#### 6. Give the number of cars of a specific company in the dataset.

In [11]:
#display(dataframe['company'].value_counts())

dataframe['company'].value_counts()['volvo']

2

#### 5. Some practicality: give example of usage of .at, .iat, .loc and .iloc.

In [16]:
print("The car and its price in the 3rd row is --> ", dataframe.at[3,"company"], dataframe.at[3,'body-style'].capitalize())
print()
print("The value in the 23th row and 7th column is --> ", dataframe.iat[23,7])
print()
print("The first 5 cars are: ")
display(dataframe.loc[0:4 , ["company"]])
print("The first 3 cars and their last 4 info are:")
display(dataframe.iloc[0:3, -4:])

The car and its price in the 3rd row is -->  audi Sedan

The value in the 23th row and 7th column is -->  70

The first 5 cars are:

       company
0  alfa-romero
1  alfa-romero
2  alfa-romero
3         audi
4         audi

The first 3 cars and their last 4 info are:

  num-of-cylinders  horsepower  average-mileage    price
0             four         111               21  13495.0
1             four         111               21  16500.0
2              six         154               19  16500.0

#### 6. Find the highest priced car for each company. Display only the company name, the type and the price of the car.

In [ ]:
auto_company = dataframe.groupby('company')['company'].count()

highest_price = auto_company[]


display(auto_company)

company
alfa-romero      3
audi             4
bmw              6
chevrolet        3
dodge            2
honda            3
isuzu            3
jaguar           3
mazda            5
mercedes-benz    4
mitsubishi       4
nissan           5
porsche          3
toyota           7
volkswagen       4
volvo            2
Name: company, dtype: int64